import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'High-Performance Wireless Headphones',
    description: 'Experience immersive sound with these noise-cancelling wireless headphones. Long-lasting battery and comfortable design for all-day use.',
    price: 199.99,
    rating: 4.8,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics headphones',
  },
  {
    id: '2',
    name: 'Smart Fitness Tracker Watch',
    description: 'Monitor your health and fitness goals with this sleek smartwatch. Tracks heart rate, steps, sleep, and more.',
    price: 89.50,
    rating: 4.5,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics watch',
  },
  {
    id: '3',
    name: 'Ultra HD 4K Action Camera',
    description: 'Capture your adventures in stunning 4K resolution. Waterproof and durable, perfect for any environment.',
    price: 249.00,
    rating: 4.7,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics camera',
  },
  {
    id: '4',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact yet powerful Bluetooth speaker with deep bass and a waterproof design. Take your music anywhere.',
    price: 59.99,
    rating: 4.6,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics speaker',
  },
  {
    id: '5',
    name: 'Ergonomic Mechanical Keyboard',
    description: 'Enhance your typing experience with this mechanical keyboard, featuring customizable RGB lighting and responsive keys.',
    price: 129.99,
    rating: 4.9,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics keyboard',
  },
  {
    id: '6',
    name: 'Professional Condenser Microphone',
    description: 'Studio-quality USB microphone perfect for streaming, podcasting, and recording music. Crystal-clear audio.',
    price: 110.00,
    rating: 4.8,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics microphone',
  },
  {
    id: '7',
    name: 'Lightweight Gaming Mouse',
    description: 'Gain a competitive edge with this ultra-lightweight gaming mouse, featuring a high-precision sensor and programmable buttons.',
    price: 79.99,
    rating: 4.7,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics mouse',
  },
  {
    id: '8',
    name: 'Curved Ultrawide Gaming Monitor',
    description: 'Immerse yourself in your games with this 34-inch curved ultrawide monitor with a high refresh rate and vibrant colors.',
    price: 799.99,
    rating: 4.8,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics monitor',
  },
  {
    id: '9',
    name: 'Modern Minimalist Desk Lamp',
    description: 'Elegant and functional LED desk lamp with adjustable brightness and color temperature. Eye-caring technology.',
    price: 45.00,
    rating: 4.4,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'home office',
  },
  {
    id: '10',
    name: 'Smart Coffee Maker with Grinder',
    description: 'Wake up to freshly brewed coffee. This smart coffee maker can be controlled from your phone.',
    price: 149.99,
    rating: 4.5,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'home kitchen',
  },
  {
    id: '11',
    name: 'Premium Leather Backpack',
    description: 'A stylish and durable backpack for work or travel, with a dedicated laptop compartment and multiple pockets.',
    price: 155.00,
    rating: 4.9,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'fashion accessory',
  },
    {
    id: '12',
    name: 'Advanced Drone with 4K Camera',
    description: 'Explore the skies and capture breathtaking aerial footage with this easy-to-fly drone featuring GPS and a 4K camera.',
    price: 599.00,
    rating: 4.7,
    imageUrl: 'https://placehold.co/600x600.png',
    productUrl: '#',
    category: 'electronics drone',
  },
];
